/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Convert a request JSON string from one format to another. */
export declare function convertRequestString(input: string, from: string, to: string): string;
/** Convert a response JSON string from one format to another. */
export declare function convertResponseString(input: string, from: string, to: string): string;
